baseURL = 'https://rosaainz.github.io/RosaSainz-Blog/'
languageCode = 'en-us'
title = 'myTechBagaje'
theme = 'blowfish'


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

