baseURL = 'https://rosaainz.github.io/RosaSainz-Blog/'
languageCode = 'en'
title = 'RosaSainz'
theme = 'blowfish'

enableRobotsTXT = true
paginate = 10
summaryLength = 30

buildDrafts = false
buildFuture = false


[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]



