title = "Rosa Sainz"
#logo = "img/murcielago.png"

[author]
name = "Rosa Sainz"
image = "img/yo.jpg"
headline = "Mi experiencia aprendiendo ingenieria de software 💫"
links = [
  { github = "https://github.com/rosaainz" },
  { twitter = "https://twitter.com/RosaaSainz" },
   { envelope = "mailto:rosagsainz.21@gmail.com" }
]