# -- Main Menu --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

  [[main]]
  name = "Experience"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20



[[main]]
  pre = "github"
  name = ""
  url = "https://github.com/rosaainz"
  weight = 30

# -- Footer Menu --
 [[footer]]
  name = "Topics"
  pageRef = "topics"
  weight = 20
