# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  pre = "github"
  name = ""
  url = "https://github.com/rosaainz"
  weight = 30

# -- Footer Menu --
 [[footer]]
  name = "Topics"
  pageRef = "topics"
  weight = 20
