# -- Main Menu --

[[main]]
  name = "Articulos"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Sobre mi"
  pageRef = "about"
  weight = 20

  [[main]]
  name = "Experiencia"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Proyectos"
  pageRef = "projects"
  weight = 20

[[main]]
  pre = "github"
  name = ""
  url = "https://github.com/rosaainz"
  weight = 30

  

# -- Footer Menu --
 [[footer]]
  name = "Topics"
  pageRef = "topics"
  weight = 20
