colorScheme = "Otoño"


[homepage]
  layout = "background"
  homepageImage = "/img/luz.jpg"
  showRecent = false
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "docs"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true